
format_version = "1.0"

-- Every ui_text key in motherboard_def.lua must have a matching entry here.
texts = {
  -- Audio I/O
  ["audio input L"]  = "Audio Input L",
  ["audio input R"]  = "Audio Input R",
  ["audio output L"] = "Audio Output L",
  ["audio output R"] = "Audio Output R",

  -- Controls
  ["Amount"]    = "Amount",
  ["Tone"]      = "Tone",
  ["Character"] = "Style",
  ["In_Level In Level"]   = "In Level",
  ["Out_Level Out Level"] = "Out Level",
  ["Level:format dB"]     = "^0 dB",
  ["Remote In_Level:short8"]  = "In Level",
  ["Remote In_Level:short4"]  = "In",
  ["Remote Out_Level:short8"] = "Out Levl",
  ["Remote Out_Level:short4"] = "Out",

  -- Model selector (16 circuits: Clean / Warm / Gritty / Heavy)
  ["Model"]      = "Model",
  ["BC12"  ] = "BC12",
  ["PV40"  ] = "PV40",
  ["TG23"  ] = "TG23",
  ["BV98"  ] = "BV98",
  ["WP76"  ] = "WP76",
  ["ZX67"  ] = "ZX67",
  ["A1R"   ] = "A1R",
  ["ES83"  ] = "ES83",
  ["FD88"  ] = "FD88",
  ["LF09"  ] = "LF09",
  ["NN18"  ] = "NN18",
  ["SB05"  ] = "SB05",
  ["FF37"  ] = "FF37",
  ["GR1T"  ] = "GR1T",
  ["F34K"  ] = "F34K",
  ["X7R3"  ] = "X7R3",

  -- CV
  ["Amount CV"]    = "Amount CV",
  ["Tone CV"]      = "Tone CV",
  ["Character CV"] = "Style CV",

  -- Meters
  ["Input Meter"]      = "Input Meter",
  ["Input Meter Peak"] = "Input Meter Peak",

  -- LFO + display (SDK 5 touch screen)
  ["Off"]                                   = "Off",
  ["On"]                                    = "On",
  ["LFO"]                                   = "LFO",
  ["LFO_On LFO"]                            = "LFO",
  ["LFO_Rate LFO Rate"]                     = "LFO Rate",
  ["LFO_Rate:format Hz"]                    = "^0 Hz",
  ["LFO_Rate_Sync LFO Sync Rate"]           = "LFO Sync Rate",
  ["LFO div 16/1"]                       = "16/1",
  ["LFO div 8/1"]                        = "8/1",
  ["LFO div 4/1"]                        = "4/1",
  ["LFO div 2/1"]                        = "2/1",
  ["LFO div 7/4"]                        = "7/4",
  ["LFO div 3/2"]                        = "3/2",
  ["LFO div 5/4"]                        = "5/4",
  ["LFO div 1/1"]                        = "1/1",
  ["LFO div 7/8"]                        = "7/8",
  ["LFO div 3/4"]                        = "3/4",
  ["LFO div 5/8"]                        = "5/8",
  ["LFO div 1/2"]                        = "1/2",
  ["LFO div 7/16"]                       = "7/16",
  ["LFO div 3/8"]                        = "3/8",
  ["LFO div 5/16"]                       = "5/16",
  ["LFO div 1/4"]                        = "1/4",
  ["LFO div 3/16"]                       = "3/16",
  ["LFO div 1/4T"]                       = "1/4T",
  ["LFO div 1/8"]                        = "1/8",
  ["LFO div 1/8T"]                       = "1/8T",
  ["LFO div 1/16"]                       = "1/16",
  ["LFO div 1/16T"]                      = "1/16T",
  ["LFO div 1/32"]                       = "1/32",
  ["LFO div 1/32T"]                      = "1/32T",
  ["LFO div 1/64"]                       = "1/64",
  ["LFO_Sync LFO Sync"]                     = "LFO Sync",
  ["LFO_Shape LFO Shape"]                   = "LFO Shape",
  ["LFO sine"]                              = "Sine",
  ["LFO triangle"]                          = "Triangle",
  ["LFO saw up"]                            = "Saw Up",
  ["LFO saw down"]                          = "Saw Down",
  ["LFO square"]                            = "Square",
  ["LFO s&h"]                               = "S&H",
  ["LFO drift"]                             = "Drift",
  ["LFO_Depth_Amount LFO > Amount"]         = "LFO > Amount",
  ["LFO_Depth_Tone LFO > Tone"]             = "LFO > Tone",
  ["LFO_Depth_Character LFO > Character"]   = "LFO > Style",
  ["LFO_Phase_Amount LFO Phase Amount"]     = "LFO Phase Amount",
  ["LFO_Phase_Tone LFO Phase Tone"]         = "LFO Phase Tone",
  ["LFO_Phase_Character LFO Phase Character"] = "LFO Phase Style",
  ["LFO_Phase:format deg"]                  = "^0 deg",
  ["UI_LfoView LFO View"]                   = "LFO View",
  ["UI_ModeList Mode List"]                 = "Mode List",
  ["Lvl_AncY Level Anchor Y"]               = "Level Anchor Y",
  ["Lvl_AncV Level Anchor Value"]           = "Level Anchor Value",
  ["Lvl_AncS Level Anchor Shift"]           = "Level Anchor Shift",
  ["Lvl_Grab Level Grab"]                   = "Level Grab",
  ["UI Edit Mask"]                          = "Edit Mask",
  ["UI CV Mask"]                            = "CV Connected",
  ["UI_Editing Editing"]                    = "Editing",
  ["group name Main"]                       = "Main",
  ["group name LFO"]                        = "LFO",
  ["UI popup clean"]                        = "Clean Models",
  ["UI popup warm"]                         = "Warm Models",
  ["UI popup gritty"]                       = "Gritty Models",
  ["UI popup heavy"]                        = "Heavy Models",
  ["UI popup shapes"]                       = "LFO Shapes",
  ["LFO Phase Out"]                         = "LFO Phase",
  ["Mod Amount Out"]                        = "Modulated Amount",
  ["Mod Tone Out"]                          = "Modulated Tone",
  ["Mod Character Out"]                     = "Modulated Style",
  ["LFO CV Out"]                            = "LFO CV Out",
  ["UI Anim Clock"]                         = "Animation Clock",
  -- Remote chart short names
  ["Remote Amount:short8"] = "Amount",
  ["Remote Amount:short4"] = "Amnt",
  ["Remote Tone:short8"] = "Tone",
  ["Remote Tone:short4"] = "Tone",
  ["Remote Character:short8"] = "Style",
  ["Remote Character:short4"] = "Styl",
  ["Remote Model:short8"] = "Model",
  ["Remote Model:short4"] = "Modl",
  ["Remote LFO_On:short8"] = "LFO On",
  ["Remote LFO_On:short4"] = "LFO",
  ["Remote LFO_Rate:short8"] = "LFO Rate",
  ["Remote LFO_Rate:short4"] = "Rate",
  ["Remote LFO_Rate_Sync:short8"] = "SyncRate",
  ["Remote LFO_Rate_Sync:short4"] = "SRat",
  ["Remote LFO_Sync:short8"] = "LFO Sync",
  ["Remote LFO_Sync:short4"] = "Sync",
  ["Remote LFO_Shape:short8"] = "LFOShape",
  ["Remote LFO_Shape:short4"] = "Shpe",
  ["Remote LFO_Depth_Amount:short8"] = "LFO>Amnt",
  ["Remote LFO_Depth_Amount:short4"] = "L>Am",
  ["Remote LFO_Depth_Tone:short8"] = "LFO>Tone",
  ["Remote LFO_Depth_Tone:short4"] = "L>To",
  ["Remote LFO_Depth_Character:short8"] = "LFO>Styl",
  ["Remote LFO_Depth_Character:short4"] = "L>St",
  ["Remote LFO_Phase_Amount:short8"] = "PhsAmnt",
  ["Remote LFO_Phase_Amount:short4"] = "PhAm",
  ["Remote LFO_Phase_Tone:short8"] = "PhsTone",
  ["Remote LFO_Phase_Tone:short4"] = "PhTo",
  ["Remote LFO_Phase_Character:short8"] = "PhsStyl",
  ["Remote LFO_Phase_Character:short4"] = "PhSt",
}
